[theme]
base = "dark"
primaryColor = "#E8EBEF"
backgroundColor = "#101214"
secondaryBackgroundColor = "#171A1E"
textColor = "#E8EAED"
font = "sans serif"

[server]
maxUploadSize = 200

[browser]
gatherUsageStats = false
